### PR TITLE
Add tvOS target

### PR DESCRIPTION
**Pull request by larsblumberg**
Hi! This PR adds tvOS to the platform targets.

### CODE REVIEW

**Comment by larsblumberg** [comment]
Hi! This PR adds tvOS to the platform targets.

**Comment by squarefrog** [comment]
Ooooh interesting! Thanks for the PR. Have you tested this on an actual device? 

I think the `podspec` bump would only help people manually targeting though as I can't push it to trunk.

**Comment by larsblumberg** [comment]
We are developing an Apple TV app, but I didn't test it yet with an actual device. As iOS and tvOS use the same SDKs, this should work. I don't see any other necessary changes yet.

Yeah, I know that you (unfortunately) can't push to trunk and I've seen that you've already created PRs for the original repo. I've just added another PR that comprise all your changes: https://github.com/sboisson/CocoaSSDP/pull/4 Let's see if the maintainer still cares.

**Comment by larsblumberg** [comment]
Thanks!

**Comment by squarefrog** [comment]
Thank you for the PR! 🎉

**Pull request merged**
